version: 1.0.1.{build}
image: Visual Studio 2019

skip_commits:
  files:
    - README.md

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- cmd: nuget restore

build:
  project: DynamicPaper.sln
  verbosity: minimal
  
cache:
  - '%USERPROFILE%\.nuget\packages -> **.sln, **.csproj'  # preserve nuget folder (packages) unless the solution or projects change
  
test: off
deploy: off
    
after_build:
  - 'appveyor-build.bat'

# override common config
for:

# config for master branch
#
-
  branches:
    only:
      - master
      - /v\d+\.\d+\.\d+/

  configuration: Release

  deploy:
    artifact: /.*\.exe/
    auth_token:
      secure: FvYSkn+t71h71KQJ3v63HzNcxv7Hv9rpqQiQ/Zdly9h87M3VmB2WexbixZg1EDIq
    draft: true
    provider: GitHub
    on:
      appveyor_repo_tag: true

  artifacts:
  - path: 'DynamicPaper-Setup_v*.exe'
    name: $(CONFIGURATION)-Setup_Build
  - path: 'stpack.exe'
    name: stpack-$(CONFIGURATION)_Build

# config for develop branch
#
-
  branches:
    only:
      - develop

  configuration:
    - Debug
    - Release

  artifacts:
  - path: DynamicPaper.zip
    name: $(CONFIGURATION)_Build
  - path: 'DynamicPaper-Setup.exe'
    name: $(CONFIGURATION)-Setup_Build
  - path: 'stpack.exe'
    name: stpack-$(CONFIGURATION)_Build
