version: 1.0.0.{build}
image: Visual Studio 2019

skip_commits:
  files:
    - README.md

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- cmd: nuget restore

build:
  project: DynamicPaper/DynamicPaper.csproj
  verbosity: minimal
  
cache:
  - '%USERPROFILE%\.nuget\packages -> **.sln, **.csproj'  # preserve nuget folder (packages) unless the solution or projects change
  
test: off
deploy: off


# override common config
for:

# config for master branch
#
-
  branches:
    only:
      - master

  configuration: Release

# config for develop branch
#
-
  branches:
    only:
      - develop
    
  configuration: Debug
  after_build:
  - cmd: >-
      mkdir "DynamicPaper_v%APPVEYOR_BUILD_VERSION%"

      xcopy "%APPVEYOR_BUILD_FOLDER%\DynamicPaper\bin\Debug" "DynamicPaper_v%APPVEYOR_BUILD_VERSION%" /E /C

      7z a "DynamicPaper_v%APPVEYOR_BUILD_VERSION%_Debug.zip" "DynamicPaper_v%APPVEYOR_BUILD_VERSION%"

  artifacts:
  - path: DynamicPaper_v$(APPVEYOR_BUILD_VERSION)_Debug.zip
    name: DynamicPaper_Debug