version: 1.0.0.{build}
image: Visual Studio 2019

skip_commits:
  files:
    - README.md

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- cmd: nuget restore

build:
  project: DynamicPaper/DynamicPaper.csproj
  verbosity: minimal
  
cache:
  - '%USERPROFILE%\.nuget\packages -> **.sln, **.csproj'  # preserve nuget folder (packages) unless the solution or projects change
  
test: off
deploy: off
    
after_build:
  - cmd: >-
      mkdir "DynamicPaper_%CONFIGURATION%_v%APPVEYOR_BUILD_VERSION%"

      xcopy "%APPVEYOR_BUILD_FOLDER%\DynamicPaper\bin\%CONFIGURATION%" "DynamicPaper_%CONFIGURATION%_v%APPVEYOR_BUILD_VERSION%" /E /C

      7z a "DynamicPaper.zip" "DynamicPaper_%CONFIGURATION%_v%APPVEYOR_BUILD_VERSION%"
 
      set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 6"
   
      iscc dynamicpaper-installer.iss /DConfiguration=%CONFIGURATION%

# override common config
for:

# config for master branch
#
-
  branches:
    only:
      - master

  configuration: Release

  deploy:
    description: 'DynamicPaper Installer'
    artifact: /.*\.exe/
    auth_token:
      secure: FvYSkn+t71h71KQJ3v63HzNcxv7Hv9rpqQiQ/Zdly9h87M3VmB2WexbixZg1EDIq
    draft: true
    provider: GitHub
    on:
      appveyor_repo_tag: true

# config for develop branch
#
-
  branches:
    only:
      - develop

  configuration:
    - Debug
    - Release

  artifacts:
  - path: DynamicPaper.zip
    name: $(CONFIGURATION)_Build
  - path: 'DynamicPaper-Setup*.exe'
    name: $(CONFIGURATION)-Setup_Build